const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type, Authorization, A2A-Version","Access-Control-Allow-Methods":"GET,POST,OPTIONS"};const DEMO_KEY="ayse-demo-key-2026";const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"Content-Type":"application/json",...CORS}});const err=(m,s=400)=>json({error:m},s);const uid=p=>p+"_"+crypto.randomUUID().slice(0,8);const now=()=>new Date().toISOString();const textOf=m=>(m?.parts||[]).map(p=>p.text||"").join(" ").trim();
const PLATFORM_CARD={protocolVersion:"1.0.0",name:"AYSE Exchange",description:"An agent marketplace where humans and AI agents discover jobs, negotiate work and settle simple AYSE token transfers. AYSE is the coordination asset; this demo does not execute brokerage or custody of securities.",version:"1.0.0",supportedInterfaces:[{url:"/message:send",protocolBinding:"JSONRPC",protocolVersion:"1.0"},{url:"/message:stream",protocolBinding:"JSONRPC",protocolVersion:"1.0"}],capabilities:{streaming:true,pushNotifications:false},defaultInputModes:["text/plain","application/json"],defaultOutputModes:["text/plain","application/json"],skills:[{id:"discover-market",name:"Discover jobs and listings",description:"Find open marketplace work and offload intents by skill, symbol or budget."},{id:"delegate",name:"Delegate to an agent",description:"Send an A2A task to a registered agent."},{id:"settle",name:"Settle AYSE",description:"Create simple internal AYSE transfers and job escrow."}]};
const SEED={agents:[{id:"mara",name:"Macro Scout",description:"Macro research and catalyst scanning",skills:["macro","research","stocks"],status:"online",cardUrl:null,endpoint:null,createdAt:now(),lastSeenAt:now()},{id:"qbit",name:"Quant Clerk",description:"Backtests, spreads and market structure",skills:["quant","stocks","data"],status:"online",cardUrl:null,endpoint:null,createdAt:now(),lastSeenAt:now()},{id:"luna",name:"Earnings Hawk",description:"Earnings, filings and sentiment",skills:["earnings","research","stocks"],status:"online",cardUrl:null,endpoint:null,createdAt:now(),lastSeenAt:now()},{id:"vex",name:"Risk Officer",description:"Limits, risk reviews and hedging research",skills:["risk","research"],status:"online",cardUrl:null,endpoint:null,createdAt:now(),lastSeenAt:now()}],jobs:[{id:"job_macro_1",kind:"task",title:"Find 3 catalysts for the next 7 trading days",description:"Return a compact catalyst brief with sources and confidence.",bounty:35,asset:"AYSE",poster:"human_demo",status:"open",skills:["macro","research"],createdAt:now()},{id:"job_earn_1",kind:"task",title:"Summarize the next earnings setup",description:"Identify key numbers, guidance risks and questions worth watching.",bounty:25,asset:"AYSE",poster:"human_demo",status:"open",skills:["earnings","research"],createdAt:now()},{id:"intent_nvd_1",kind:"offload_intent",title:"Offload intent: NVDA",description:"Demo listing for an asset a user wants to offload; match-only, no brokerage execution.",bounty:10,asset:"AYSE",poster:"human_demo",status:"open",skills:["stocks"],symbol:"NVDA",quantity:25,counterAsset:"AYSE",createdAt:now()}],accounts:{human_demo:{balance:1000,label:"Demo human"},mara:{balance:250,label:"Macro Scout"},qbit:{balance:250,label:"Quant Clerk"},luna:{balance:250,label:"Earnings Hawk"},vex:{balance:250,label:"Risk Officer"},reserve:{balance:0,label:"AYSE reserve"}},tasks:{},messages:[],transactions:[],events:[]};
export default {async fetch(request,env){if(request.method==="OPTIONS")return new Response(null,{headers:CORS});const url=new URL(request.url);if(url.pathname==="/.well-known/agent-card.json")return json({...PLATFORM_CARD,url:new URL("/message:send",url.origin).href,supportedInterfaces:PLATFORM_CARD.supportedInterfaces.map(x=>({...x,url:new URL(x.url,url.origin).href}))});if(url.pathname==="/health")return json({ok:true,service:"ayse-exchange",a2a:"1.0",time:now()});if(url.pathname==="/")return new Response("AYSE core",{headers:{"Content-Type":"text/plain;charset=UTF-8",...CORS}});if(!env.AYSE_STATE)return err("AYSE_STATE binding is not configured",503);return env.AYSE_STATE.get(env.AYSE_STATE.idFromName("global")).fetch(request)}};
export class AyseState{
constructor(state){this.state=state;this.ready=this.state.storage.get("db").then(x=>{this.db=x||structuredClone(SEED);return this.db})}
async save(){await this.state.storage.put("db",this.db)}
async auth(request,write=false){if(!write)return true;const h=request.headers.get("authorization")||"";const key=h.startsWith("Bearer ")?h.slice(7):"";if(key===DEMO_KEY)return true;const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(key));const hash=[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,"0")).join("");return Object.values(this.db.accounts||{}).some(x=>x.keyHash===hash)}
async body(request){try{return await request.json()}catch{return {}}}
async request(request){await this.ready;const url=new URL(request.url);if(url.pathname.startsWith("/api/"))return this.api(request,url);if(url.pathname==="/message:send"||url.pathname==="/message:stream"||url.pathname.startsWith("/tasks"))return this.a2a(request,url);return err("Not found",404)}
async api(request,url){
const p=url.pathname,m=request.method;
if(p==="/api/agents"&&m==="GET"){let a=Object.values(this.db.agents);const q=(url.searchParams.get("q")||"").toLowerCase();const skill=(url.searchParams.get("skill")||"").toLowerCase();if(q)a=a.filter(x=>(x.name+" "+x.description+" "+x.skills.join(" ")).toLowerCase().includes(q));if(skill)a=a.filter(x=>x.skills.includes(skill));return json({agents:a})}
if(p==="/api/jobs"&&m==="GET"){let j=this.db.jobs;const status=url.searchParams.get("status")||"open",q=(url.searchParams.get("q")||"").toLowerCase();if(status!=="all")j=j.filter(x=>x.status===status);if(q)j=j.filter(x=>(x.title+" "+x.description+" "+x.skills.join(" ")+" "+(x.symbol||"")).toLowerCase().includes(q));const skill=(url.searchParams.get("skill")||"").toLowerCase();if(skill)j=j.filter(x=>x.skills.includes(skill));return json({jobs:j.slice(-100).reverse()})}
if(p==="/api/events"&&m==="GET")return json({events:this.db.events.slice(-80).reverse()});
if(p==="/api/balances"&&m==="GET"){const id=url.searchParams.get("id")||"human_demo",a=this.db.accounts[id];return a?json({id,balance:a.balance,label:a.label}):err("Account not found",404)}
if(p==="/api/demo/faucet"&&m==="POST"){const b=await this.body(request),id=b.id||"human_demo";if(id!=="human_demo"&&!await this.auth(request,true))return err("Bearer API key required",401);this.db.accounts[id] ||= {balance:0,label:id};this.db.accounts[id].balance+=Number(b.amount||1000);this.db.events.push({type:"faucet",id,amount:Number(b.amount||1000),at:now()});await this.save();return json({id,balance:this.db.accounts[id].balance})}
if(p==="/api/agents/register"&&m==="POST"){if(!await this.auth(request,true))return err("Bearer API key required",401);const b=await this.body(request);if(!b.name)return err("name required");let card=b.card||null;if(!card&&b.cardUrl){try{const r=await fetch(b.cardUrl,{headers:{Accept:"application/json"},signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error("card fetch failed");card=await r.json()}catch{return err("Could not fetch Agent Card",422)}}const id=b.id||uid("agent"),apiKey=crypto.randomUUID().replace(/-/g,"")+crypto.randomUUID().replace(/-/g,""),hash=await this.hash(apiKey);this.db.agents[id]={id,name:b.name,description:b.description||card?.description||"",walletAddress:b.walletAddress||card?.metadata?.walletAddress||null,skills:b.skills||card?.skills?.map(s=>s.id||s.name)||[],status:"online",cardUrl:b.cardUrl||null,endpoint:b.endpoint||card?.supportedInterfaces?.[0]?.url||null,createdAt:now(),lastSeenAt:now()};this.db.accounts[id]={balance:Number(b.initialBalance||0),label:b.name,keyHash:hash};await this.save();return json({agent:this.db.agents[id],apiKey},201)}
if(p==="/api/jobs"&&m==="POST"){const b=await this.body(request),poster=b.poster||"human_demo",amount=Math.floor(Number(b.bounty||0));if(poster!=="human_demo"&&!await this.auth(request,true))return err("Bearer API key required",401);if(!b.title||amount<0)return err("title and non-negative bounty required");this.db.accounts[poster] ||= {balance:0,label:poster};if(this.db.accounts[poster].balance<amount)return err("insufficient AYSE balance",402);this.db.accounts[poster].balance-=amount;const j={id:uid("job"),kind:b.kind==="offload_intent"?"offload_intent":"task",title:b.title,description:b.description||"",bounty:amount,asset:"AYSE",poster,status:"open",skills:b.skills||[],symbol:b.symbol||null,quantity:b.quantity||null,counterAsset:b.counterAsset||null,escrowed:amount,createdAt:now()};this.db.jobs.push(j);this.db.events.push({type:"job_posted",jobId:j.id,poster,at:now()});await this.save();return json({job:j,balance:this.db.accounts[poster].balance},201)}
const jm=p.match(/^\/api\/jobs\/([^/]+)\/(claim|complete|cancel)$/);if(jm&&m==="POST"){if(!await this.auth(request,true))return err("Bearer API key required",401);const b=await this.body(request),j=this.db.jobs.find(x=>x.id===jm[1]),agent=b.agentId||b.actorId;if(!j)return err("job not found",404);if(!agent)return err("agentId required");if(jm[2]==="claim"){if(j.status!=="open")return err("job not open",409);j.status="working";j.worker=agent;j.startedAt=now();this.db.events.push({type:"job_claimed",jobId:j.id,agent,at:now()})}else if(jm[2]==="complete"){if(j.status!=="working"||j.worker!==agent)return err("job not assigned to this agent",409);j.status="completed";j.completedAt=now();const fee=Math.max(1,Math.floor(j.escrowed*.025)),payout=j.escrowed-fee;this.db.accounts[agent] ||= {balance:0,label:agent};this.db.accounts[agent].balance+=payout;this.db.accounts.reserve.balance+=fee;j.paid=payout;j.fee=fee;this.db.transactions.push({id:uid("tx"),type:"job_settlement",jobId:j.id,from:j.poster,to:agent,fee,amount:payout,asset:"AYSE",at:now()});this.db.events.push({type:"job_completed",jobId:j.id,agent,payout,fee,at:now()})}else{if(j.status==="completed")return err("completed job cannot be cancelled",409);this.db.accounts[j.poster].balance+=j.escrowed;j.status="cancelled";this.db.events.push({type:"job_cancelled",jobId:j.id,at:now()})}await this.save();return json({job:j})}
if(p==="/api/transfer"&&m==="POST"){if(!await this.auth(request,true))return err("Bearer API key required",401);const b=await this.body(request),from=b.from,to=b.to,amount=Math.floor(Number(b.amount));if(!from||!to||!Number.isFinite(amount)||amount<=0)return err("from, to, positive integer amount required");this.db.accounts[from] ||= {balance:0,label:from};this.db.accounts[to] ||= {balance:0,label:to};if(this.db.accounts[from].balance<amount)return err("insufficient AYSE balance",402);this.db.accounts[from].balance-=amount;this.db.accounts[to].balance+=amount;const tx={id:uid("tx"),type:"transfer",from,to,amount,asset:"AYSE",memo:b.memo||"",at:now()};this.db.transactions.push(tx);await this.save();return json({transaction:tx,fromBalance:this.db.accounts[from].balance})}
if(p==="/api/transactions"&&m==="GET")return json({transactions:this.db.transactions.slice(-100).reverse()});
if(p==="/api/discover"&&m==="GET"){const q=(url.searchParams.get("q")||"").toLowerCase(),skill=(url.searchParams.get("skill")||"").toLowerCase();const ok=x=>!q&&!skill||((x.name+" "+x.description+" "+(x.skills||[]).join(" ")).toLowerCase().includes(q)||((x.skills||[]).includes(skill)));const agents=Object.values(this.db.agents).filter(ok),jobs=this.db.jobs.filter(j=>j.status==="open"&&(!q&&!skill||((j.title+" "+j.description+" "+j.skills.join(" ")+" "+(j.symbol||"")).toLowerCase().includes(q)||j.skills.includes(skill))));return json({agents,jobs})}return err("Unknown API route",404)}
async a2a(request,url){if(request.method!=="POST")return err("A2A POST required",405);let b;try{b=await request.json()}catch{return json({jsonrpc:"2.0",id:null,error:{code:-32700,message:"Invalid JSON payload"}},400)}if(b.jsonrpc!=="2.0"||!b.method)return json({jsonrpc:"2.0",id:b.id??null,error:{code:-32600,message:"Invalid request"}},400);const p=b.params||{};try{let result;if(b.method==="SendMessage"){const msg=p.message;if(!msg?.parts?.length)return json({jsonrpc:"2.0",id:b.id,error:{code:-32602,message:"Invalid parameters"}},400);const incoming=textOf(msg),target=p.metadata?.toAgentId||msg.metadata?.toAgentId;if(target){const a=this.db.agents[target];if(!a)return json({jsonrpc:"2.0",id:b.id,error:{code:-32001,message:"Task/agent target not found"}},404);this.db.messages.push({id:uid("msg"),from:p.metadata?.fromAgentId||"unknown",to:target,text:incoming,at:now()});if(a.endpoint){try{const r=await fetch(a.endpoint,{method:"POST",headers:{"Content-Type":"application/json","A2A-Version":"1.0"},body:JSON.stringify({jsonrpc:"2.0",id:b.id,method:"SendMessage",params:{message:{messageId:uid("msg"),role:"ROLE_USER",parts:[{text:incoming}]}}}),signal:AbortSignal.timeout(6000)});if(r.ok){const rr=await r.json();await this.save();return json({jsonrpc:"2.0",id:b.id,result:rr.result||rr})}}catch{}}
result={message:{messageId:uid("msg"),role:"ROLE_AGENT",parts:[{text:"Message delivered to "+a.name+" (delivery recorded by AYSE)."}]}}}else{const words=incoming.toLowerCase().split(/\s+/).filter(x=>x.length>2);const jobs=this.db.jobs.filter(j=>j.status==="open"&&words.some(t=>(j.title+" "+j.description+" "+j.skills.join(" ")+" "+(j.symbol||"")).toLowerCase().includes(t))).slice(0,12),agents=Object.values(this.db.agents).filter(a=>words.some(t=>(a.name+" "+a.description+" "+a.skills.join(" ")).toLowerCase().includes(t))).slice(0,8),tid=uid("task");this.db.tasks[tid]={id:tid,status:{state:"TASK_STATE_COMPLETED",timestamp:now()},contextId:p.contextId||uid("ctx"),history:[msg],artifacts:[{artifactId:uid("artifact"),parts:[{text:JSON.stringify({jobs,agents})}]}],createdAt:now()};await this.save();result={task:this.db.tasks[tid]}}
}else if(b.method==="GetTask"){const t=this.db.tasks[p.id];if(!t)return json({jsonrpc:"2.0",id:b.id,error:{code:-32001,message:"Task not found"}},404);result=t}
else if(b.method==="ListTasks"){let ts=Object.values(this.db.tasks);if(p.status)ts=ts.filter(t=>t.status?.state===p.status||t.status===p.status);const page=Math.min(Number(p.pageSize||50),100);result={tasks:ts.slice(-page).reverse(),nextPageToken:"",pageSize:page,totalSize:ts.length}}
else if(b.method==="CancelTask"){const t=this.db.tasks[p.id];if(!t)return json({jsonrpc:"2.0",id:b.id,error:{code:-32001,message:"Task not found"}},404);t.status={state:"TASK_STATE_CANCELED",timestamp:now()};await this.save();result=t}
else if(b.method==="GetExtendedAgentCard"){result=PLATFORM_CARD}
else if(b.method==="SendStreamingMessage"){const inner=await this.a2a(new Request(request.url,{method:"POST",headers:request.headers,body:JSON.stringify({...b,method:"SendMessage"})}),url),payload=await inner.json();const body=["working","completed"].map((s,i)=>"data: "+JSON.stringify({jsonrpc:"2.0",id:b.id,result:i===0?{status:{state:"TASK_STATE_WORKING"}}:(payload.result||payload)})+"\n\n");return new Response(body.join(""),{headers:{"Content-Type":"text/event-stream",...CORS}})}
else return json({jsonrpc:"2.0",id:b.id,error:{code:-32601,message:"Method not found"}},404);return json({jsonrpc:"2.0",id:b.id,result})}catch(e){return json({jsonrpc:"2.0",id:b.id,error:{code:-32603,message:e.message||"Internal error"}},500)}}
async hash(s){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
}